<?php
/**
 * index.php
 * Frontend Entry Point
 */

require_once __DIR__ . '/src/config.php';

$cacheBuster = time();
$appName = PROJECT_NAME;
$appTagline = PROJECT_TAGLINE;
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title><?= htmlspecialchars($appName) ?> - <?= htmlspecialchars($appTagline) ?></title>
    <meta name="description" content="Master your interviews with AI that researches your interviewers and provides personalized mock interviews with detailed feedback.">
    <link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>&#127919;</text></svg>">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="css/core/base.css?v=<?= $cacheBuster ?>">
    <link rel="stylesheet" href="css/core/components.css?v=<?= $cacheBuster ?>">
    <link rel="stylesheet" href="css/core/layout.css?v=<?= $cacheBuster ?>">
    <link rel="stylesheet" href="css/pages/home.css?v=<?= $cacheBuster ?>">
    <link rel="stylesheet" href="css/pages/prepare.css?v=<?= $cacheBuster ?>">
    <link rel="stylesheet" href="css/pages/interview.css?v=<?= $cacheBuster ?>">
    <link rel="stylesheet" href="css/pages/feedback.css?v=<?= $cacheBuster ?>">
    <link rel="stylesheet" href="css/features/history.css?v=<?= $cacheBuster ?>">
    <link rel="stylesheet" href="css/features/share.css?v=<?= $cacheBuster ?>">
    <link rel="stylesheet" href="css/overrides/responsive.css?v=<?= $cacheBuster ?>">
    <link rel="stylesheet" href="css/overrides/print.css?v=<?= $cacheBuster ?>" media="print">
    <style>
        :root {
            --app-print-header: "<?= htmlspecialchars($appName) ?> - Interview Feedback Report";
            --app-print-footer: "Generated by <?= htmlspecialchars($appName) ?> - <?= htmlspecialchars($appTagline) ?>";
        }
    </style>
</head>
<body>
    <div class="bg-shapes">
        <div class="bg-shape bg-shape-1"></div>
        <div class="bg-shape bg-shape-2"></div>
        <div class="bg-shape bg-shape-3"></div>
    </div>

    <div id="app">
        <header class="header">
            <div class="header-content">
                <div class="logo" id="logo-home">
                    <span class="logo-text" id="app-name"><?= htmlspecialchars($appName) ?></span>
                </div>
                <nav class="nav">
                    <button class="nav-btn active" data-section="home" data-i18n="nav.home">Home</button>
                    <button class="nav-btn" data-section="prepare" data-i18n="nav.prepare">Prepare</button>
                    <button class="nav-btn disabled" data-section="interview" disabled data-i18n="nav.interview">Interview</button>
                    <button class="nav-btn disabled" data-section="feedback" disabled data-i18n="nav.feedback">Feedback</button>
                </nav>
                <select id="language-select" class="lang-select">
                    <option value="en">&#127468;&#127463; EN</option>
                    <option value="fr">&#127467;&#127479; FR</option>
                </select>
            </div>
        </header>

        <section id="section-home" class="section active">
            <div class="hero">
                <div class="hero-content">
                    <div class="hero-badge">
                        <span class="badge-icon">&#10024;</span>
                        <span data-i18n="hero.badge">Powered by Google Gemini 3</span>
                    </div>
                    <h1 class="hero-title">
                        <span data-i18n="hero.title.part1">Master Your Interview with</span>
                        <span class="gradient-text" data-i18n="hero.title.part2">AI-Powered</span>
                        <span data-i18n="hero.title.part3">Preparation</span>
                    </h1>
                    <p class="hero-subtitle" data-i18n="hero.subtitle">Upload your CV and job description. We'll research your interviewers, generate personalized questions, and conduct realistic mock interviews with voice and video analysis.</p>
                    <div class="hero-actions">
                        <button class="btn btn-primary btn-lg btn-glow" id="btn-start-preparing">
                            <span>&#128640;</span> <span data-i18n="hero.cta.start">Start Preparing</span>
                        </button>
                        <button class="btn btn-secondary btn-lg" id="btn-learn-more">
                            <span>&#128161;</span> <span data-i18n="hero.cta.learn">Learn More</span>
                        </button>
                    </div>
                </div>
                <div class="hero-visual">
                    <div class="hero-card glass-card">
                        <div class="hero-card-header">
                            <div class="avatar-icon">
                                <span>&#127908;</span>
                            </div>
                            <div>
                                <div class="hero-card-title" data-i18n="hero.card.title">Mock Interview</div>
                                <div class="hero-card-subtitle" data-i18n="hero.card.subtitle">AI-Powered Practice Session</div>
                            </div>
                        </div>
                        <div class="chat-preview">
                            <div class="chat-msg interviewer">
                                <span class="msg-icon">&#129302;</span>
                                <span data-i18n="hero.chat.q1">Tell me about a challenging project you led...</span>
                            </div>
                            <div class="chat-msg candidate">
                                <span data-i18n="hero.chat.a1">At my previous role, I spearheaded a team of 8 engineers...</span>
                                <span class="msg-icon">&#128100;</span>
                            </div>
                            <div class="chat-msg interviewer">
                                <span class="msg-icon">&#129302;</span>
                                <span data-i18n="hero.chat.q2">How did you handle conflicts within the team?</span>
                            </div>
                        </div>
                        <div class="hero-card-stats">
                            <div class="stat-item">
                                <span class="stat-value">95%</span>
                                <span class="stat-label" data-i18n="hero.stat.confidence">Confidence</span>
                            </div>
                            <div class="stat-item">
                                <span class="stat-value">4/10</span>
                                <span class="stat-label" data-i18n="hero.stat.questions">Questions</span>
                            </div>
                            <div class="stat-item">
                                <span class="stat-value">12:34</span>
                                <span class="stat-label" data-i18n="hero.stat.duration">Duration</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- History Section (dynamically populated) -->
            <div id="history-container"></div>
            
            <div class="features">
                <h2 class="section-title"><span data-i18n="features.title.part1">Everything You Need to</span> <span class="gradient-text" data-i18n="features.title.part2">Succeed</span></h2>
                <div class="features-grid">
                    <div class="feature-card glass-card">
                        <div class="feature-icon-wrap">
                            <span class="feature-icon">&#128196;</span>
                        </div>
                        <h3 data-i18n="feature.cv.title">Smart CV Analysis</h3>
                        <p data-i18n="feature.cv.desc">AI extracts your achievements, skills, and experiences to create personalized interview scenarios</p>
                    </div>
                    <div class="feature-card glass-card">
                        <div class="feature-icon-wrap">
                            <span class="feature-icon">&#128269;</span>
                        </div>
                        <h3 data-i18n="feature.research.title">Interviewer Research</h3>
                        <p data-i18n="feature.research.desc">Web search powered by Google finds their background, interests, and likely questions</p>
                    </div>
                    <div class="feature-card glass-card">
                        <div class="feature-icon-wrap">
                            <span class="feature-icon">&#127919;</span>
                        </div>
                        <h3 data-i18n="feature.gap.title">Gap Analysis</h3>
                        <p data-i18n="feature.gap.desc">Identify skill gaps with tailored strategies to address them during your interview</p>
                    </div>
                    <div class="feature-card glass-card">
                        <div class="feature-icon-wrap">
                            <span class="feature-icon">&#127908;</span>
                        </div>
                        <h3 data-i18n="feature.voice.title">Voice Interview</h3>
                        <p data-i18n="feature.voice.desc">Practice speaking with real-time transcription and speech analytics</p>
                    </div>
                    <div class="feature-card glass-card">
                        <div class="feature-icon-wrap">
                            <span class="feature-icon">&#128249;</span>
                        </div>
                        <h3 data-i18n="feature.video.title">Video Analysis</h3>
                        <p data-i18n="feature.video.desc">AI feedback on body language, eye contact, and confidence presentation</p>
                    </div>
                    <div class="feature-card glass-card">
                        <div class="feature-icon-wrap">
                            <span class="feature-icon">&#128202;</span>
                        </div>
                        <h3 data-i18n="feature.feedback.title">Detailed Feedback</h3>
                        <p data-i18n="feature.feedback.desc">Comprehensive scores with actionable improvement tips and ideal answers</p>
                    </div>
                </div>
            </div>
        </section>

        <section id="section-prepare" class="section">
            <div class="prepare-container">
                <div class="steps-progress">
                    <div class="step active" data-step="1">
                        <div class="step-num">1</div>
                        <span data-i18n="prepare.step.cv">CV</span>
                    </div>
                    <div class="step-line"></div>
                    <div class="step" data-step="2">
                        <div class="step-num">2</div>
                        <span data-i18n="prepare.step.job">Job</span>
                    </div>
                    <div class="step-line"></div>
                    <div class="step" data-step="3">
                        <div class="step-num">3</div>
                        <span data-i18n="prepare.step.interviewers">Interviewers</span>
                    </div>
                    <div class="step-line"></div>
                    <div class="step" data-step="4">
                        <div class="step-num">4</div>
                        <span data-i18n="prepare.step.ready">Ready</span>
                    </div>
                </div>

                <div class="prep-step active" data-step="1">
                    <div class="upload-card glass-card">
                        <div class="upload-icon">&#128196;</div>
                        <h3 data-i18n="cv.title">Upload Your CV</h3>
                        <p data-i18n="cv.subtitle">We'll analyze your experience, skills, and achievements</p>
                        <div class="upload-zone" id="cv-zone">
                            <input type="file" id="cv-file" accept=".pdf,.doc,.docx,.txt">
                            <div class="upload-zone-content">
                                <div class="upload-zone-icon">&#128228;</div>
                                <div class="upload-zone-text" data-i18n="cv.upload.text">Click or drag your CV here</div>
                                <div class="upload-zone-hint" data-i18n="cv.upload.hint">Supports PDF, DOC, DOCX, TXT</div>
                                <div class="upload-zone-formats">
                                    <span>PDF</span>
                                    <span>DOC</span>
                                    <span>DOCX</span>
                                    <span>TXT</span>
                                </div>
                            </div>
                        </div>
                        <div class="file-preview hidden" id="cv-preview">
                            <div class="file-preview-list" id="cv-file-list"></div>
                        </div>
                        <div class="result-box hidden" id="cv-result"></div>
                    </div>
                    <div class="step-actions">
                        <button class="btn btn-primary btn-lg" id="btn-next-1" disabled>
                            <span data-i18n="btn.next">Next</span> <span>&#8594;</span>
                        </button>
                    </div>
                </div>

                <div class="prep-step" data-step="2">
                    <div class="upload-card glass-card">
                        <div class="upload-icon">&#128203;</div>
                        <h3 data-i18n="jd.title">Job Description</h3>
                        <p data-i18n="jd.subtitle">Upload a file or paste the job description text</p>
                        <div class="tabs">
                            <button class="tab active" data-tab="upload" data-i18n="jd.tab.upload">Upload File</button>
                            <button class="tab" data-tab="paste" data-i18n="jd.tab.paste">Paste Text</button>
                        </div>
                        <div class="tab-panel active" data-tab="upload">
                            <div class="upload-zone" id="jd-zone">
                                <input type="file" id="jd-file" accept=".pdf,.doc,.docx,.txt">
                                <div class="upload-zone-content">
                                    <div class="upload-zone-icon">&#128228;</div>
                                    <div class="upload-zone-text" data-i18n="jd.upload.text">Click or drag JD here</div>
                                    <div class="upload-zone-formats">
                                        <span>PDF</span>
                                        <span>DOC</span>
                                        <span>DOCX</span>
                                        <span>TXT</span>
                                    </div>
                                </div>
                            </div>
                            <div class="file-preview hidden" id="jd-preview">
                                <div class="file-preview-list" id="jd-file-list"></div>
                            </div>
                        </div>
                        <div class="tab-panel" data-tab="paste">
                            <textarea id="jd-text" data-i18n-placeholder="jd.placeholder" placeholder="Paste the job description here..." rows="8"></textarea>
                        </div>
                        <div class="result-box hidden" id="jd-result"></div>
                    </div>
                    <div class="step-actions">
                        <button class="btn btn-secondary btn-lg" id="btn-back-2">
                            <span>&#8592;</span> <span data-i18n="btn.back">Back</span>
                        </button>
                        <button class="btn btn-primary btn-lg" id="btn-next-2" disabled>
                            <span data-i18n="btn.next">Next</span> <span>&#8594;</span>
                        </button>
                    </div>
                </div>

                <div class="prep-step" data-step="3">
                    <div class="upload-card glass-card">
                        <div class="upload-icon">&#128101;</div>
                        <div class="step-header-with-badge">
                            <h3 data-i18n="interviewers.title">Interviewer Research</h3>
                            <span class="optional-badge" data-i18n="interviewers.optional">Optional</span>
                        </div>
                        <p data-i18n="interviewers.subtitle">Add interviewers to research their background and tailor questions</p>
                        <p class="interviewer-hint" data-i18n="interviewers.hint">Only add interviewers with a strong public profile (executives, speakers, published authors). If the person has little online presence, skip this step to avoid inaccurate personalization.</p>
                        <div class="interviewers-container" id="interviewers-list">
                            <div class="interviewer-group">
                                <div class="interviewer-group-header">
                                    <div class="interviewer-group-title">
                                        <span>&#128100;</span>
                                        <div><span data-i18n="interviewers.label">Interviewer</span> <span class="interviewer-number">1</span></div>
                                    </div>
                                    <button class="interviewer-remove">&#215;</button>
                                </div>
                                <div class="interviewer-fields">
                                    <input type="text" class="input int-name" data-i18n-placeholder="interviewers.name" placeholder="Full Name (e.g., Demis Hassabis)">
                                    <input type="text" class="input int-company" data-i18n-placeholder="interviewers.company" placeholder="Company (e.g., Google DeepMind)">
                                    <input type="text" class="input int-role" data-i18n-placeholder="interviewers.role" placeholder="Role (optional)">
                                </div>
                            </div>
                        </div>
                        <button id="add-interviewer-btn" class="btn btn-ghost btn-sm">
                            <span>+</span> <span data-i18n="interviewers.add">Add Another Interviewer</span>
                        </button>
                    </div>
                    <div class="step-actions">
                        <button class="btn btn-secondary btn-lg" id="btn-back-3">
                            <span>&#8592;</span> <span data-i18n="btn.back">Back</span>
                        </button>
                        <button class="btn btn-ghost btn-lg" id="btn-skip-step">
                            <span>&#8594;</span> <span data-i18n="btn.skip.step">Skip &amp; Continue</span>
                        </button>
                        <button class="btn btn-primary btn-lg" id="btn-research">
                            <span>&#128269;</span> <span data-i18n="btn.research">Research &amp; Prepare</span>
                        </button>
                    </div>
                </div>

                <div class="prep-step" data-step="4">
                    <div class="ready-card glass-card">
                        <div class="ready-icon-small">&#9989;</div>
                        <h3 class="ready-title-small" data-i18n="ready.title">You're Ready!</h3>
                        <p class="ready-subtitle" data-i18n="ready.subtitle">Your interview preparation is complete</p>
                        <div id="match-summary" class="match-summary"></div>
                        
                        <h4 class="config-title" data-i18n="ready.type.title">Interview Type</h4>
                        <div class="type-grid">
                            <label class="type-card">
                                <input type="radio" name="int-type" value="full" checked>
                                <div class="type-content">
                                    <span class="type-icon">&#128203;</span>
                                    <span class="type-name" data-i18n="ready.type.full">Full</span>
                                    <span class="type-desc"><span class="type-questions" data-type="full"></span> <span data-i18n="ready.questions">questions</span></span>
                                </div>
                            </label>
                            <label class="type-card">
                                <input type="radio" name="int-type" value="behavioral">
                                <div class="type-content">
                                    <span class="type-icon">&#128172;</span>
                                    <span class="type-name" data-i18n="ready.type.behavioral">Behavioral</span>
                                    <span class="type-desc"><span class="type-questions" data-type="behavioral"></span> <span data-i18n="ready.questions">questions</span></span>
                                </div>
                            </label>
                            <label class="type-card">
                                <input type="radio" name="int-type" value="technical">
                                <div class="type-content">
                                    <span class="type-icon">&#129504;</span>
                                    <span class="type-name" data-i18n="ready.type.technical">Technical</span>
                                    <span class="type-desc"><span class="type-questions" data-type="technical"></span> <span data-i18n="ready.questions">questions</span></span>
                                </div>
                            </label>
                            <label class="type-card">
                                <input type="radio" name="int-type" value="quick">
                                <div class="type-content">
                                    <span class="type-icon">&#9889;</span>
                                    <span class="type-name" data-i18n="ready.type.quick">Quick</span>
                                    <span class="type-desc"><span class="type-questions" data-type="quick"></span> <span data-i18n="ready.questions">questions</span></span>
                                </div>
                            </label>
                        </div>
                        
                        <h4 class="config-title" data-i18n="ready.style.title">Question Style</h4>
                        <div class="style-select">
                            <select id="question-style" class="input">
                                <option value="concise">&#9889; Concise - Short, direct questions</option>
                                <option value="balanced" selected>&#128172; Balanced - Natural conversation</option>
                                <option value="detailed">&#128269; Detailed - Full context &amp; scenarios</option>
                            </select>
                        </div>
                        
                        <div class="options-row">
                            <label class="checkbox">
                                <input type="checkbox" id="opt-voice" checked>
                                <span class="checkbox-mark"></span>
                                <span>&#127908; <span data-i18n="ready.voice">Voice Mode</span></span>
                            </label>
                            <label class="checkbox">
                                <input type="checkbox" id="opt-video" checked>
                                <span class="checkbox-mark"></span>
                                <span>&#128249; <span data-i18n="ready.video">Video Analysis</span></span>
                            </label>
                        </div>
                        <div class="tts-engine-row" id="tts-engine-row">
                            <label class="config-label" data-i18n="ready.tts.label">Voice Engine</label>
                            <select id="opt-tts-engine" class="input input-sm">
                                <option value="browser" data-i18n="ready.tts.browser">&#127760; Browser (fast, no limit)</option>
                                <option value="gemini" data-i18n="ready.tts.gemini">&#10024; Gemini AI (natural, API quota)</option>
                            </select>
                        </div>
                    </div>
                    <div class="step-actions">
                        <button class="btn btn-secondary btn-lg" id="btn-back-4">
                            <span>&#8592;</span> <span data-i18n="btn.back">Back</span>
                        </button>
                        <button class="btn btn-primary btn-lg btn-glow" id="btn-start-interview">
                            <span>&#127919;</span> <span data-i18n="btn.start">Start Interview</span>
                        </button>
                    </div>
                </div>
            </div>
        </section>

        <section id="section-interview" class="section">
            <div class="interview-container">
                <div class="interview-header glass-card">
                    <div class="int-info">
                        <div class="int-avatar" id="int-avatar">&#128100;</div>
                        <div class="int-details">
                            <div class="int-name-row">
                                <div class="int-name" id="interviewer-name">Interviewer</div>
                                <div class="speaking-indicator" id="speaking-indicator">
                                    <span class="dot"></span>
                                    <span class="dot"></span>
                                    <span class="dot"></span>
                                </div>
                            </div>
                            <div class="int-role" id="interviewer-role"></div>
                        </div>
                        <div class="interviewer-selector"></div>
                    </div>
                    <div class="int-stats">
                        <div class="stat">
                            <span class="stat-label" data-i18n="interview.stat.question">Question</span>
                            <span class="stat-value" id="q-count">0/0</span>
                        </div>
                        <div class="stat">
                            <span class="stat-label" data-i18n="interview.stat.time">Time</span>
                            <span class="stat-value" id="timer">00:00</span>
                        </div>
                    </div>
                    <div class="interview-header-buttons">
                        <button class="btn btn-secondary btn-sm" id="btn-reset-interview">
                            <span>&#128260;</span> <span data-i18n="btn.reset">Restart</span>
                        </button>
                        <button class="btn btn-danger btn-sm" id="btn-end-interview">
                            <span data-i18n="btn.end">End Interview</span>
                        </button>
                    </div>
                </div>
                
                <div class="interview-main">
                    <div class="video-panel" id="video-panel">
                        <video id="user-video" autoplay muted playsinline></video>
                        <div class="video-overlay">
                            <span>&#128247;</span>
                            <span data-i18n="interview.video.off">Camera Off</span>
                        </div>
                    </div>
                    <div class="chat-panel glass-card">
                        <div class="chat-messages" id="chat-messages"></div>
                        <div class="response-area">
                            <div class="response-controls">
                                <div class="mode-tabs">
                                    <button class="mode-btn active" data-mode="voice">&#127908; <span data-i18n="interview.mode.voice">Voice</span></button>
                                    <button class="mode-btn" data-mode="text">&#9000;&#65039; <span data-i18n="interview.mode.text">Text</span></button>
                                </div>
                                <div class="input-wrapper">
                                    <div class="input-area">
                                        <div class="voice-mode active" id="voice-mode">
                                            <button class="record-btn" id="record-btn">
                                                <span class="rec-icon">&#127908;</span>
                                                <span class="rec-text" data-i18n="interview.record">Click to Speak</span>
                                                <div class="audio-visualizer">
                                                    <div class="audio-bar" data-index="0"></div>
                                                    <div class="audio-bar" data-index="1"></div>
                                                    <div class="audio-bar" data-index="2"></div>
                                                    <div class="audio-bar" data-index="3"></div>
                                                    <div class="audio-bar" data-index="4"></div>
                                                </div>
                                            </button>
                                        </div>
                                        <div class="text-mode" id="text-mode">
                                            <textarea id="response-text" data-i18n-placeholder="interview.type" placeholder="Type your response..."></textarea>
                                        </div>
                                    </div>
                                    <div class="response-buttons">
                                        <button class="btn btn-primary" id="btn-send" data-i18n="btn.send">Send</button>
                                        <button class="skip-btn" id="btn-skip">&#9197; <span data-i18n="btn.skip">Skip</span></button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section id="section-feedback" class="section">
            <div class="feedback-container">
                <div class="feedback-loading" id="feedback-loading">
                    <div class="spinner"></div>
                    <p data-i18n="feedback.loading">Analyzing your interview performance...</p>
                    <span class="loading-hint" data-i18n="feedback.loading.hint">This may take a moment</span>
                </div>
                <div class="feedback-content hidden" id="feedback-content">
                    <div class="score-card glass-card">
                        <div class="overall-score">
                            <div class="score-circle" id="score-circle" style="--score: 0">
                                <span id="score-value">0</span>
                            </div>
                            <span class="score-label" data-i18n="feedback.score">Overall Score</span>
                        </div>
                        <div class="score-bars">
                            <div class="bar-item">
                                <span data-i18n="feedback.content">Content</span>
                                <div class="bar">
                                    <div class="bar-fill" id="bar-content"></div>
                                </div>
                                <span id="score-content">0</span>
                            </div>
                            <div class="bar-item">
                                <span data-i18n="feedback.delivery">Delivery</span>
                                <div class="bar">
                                    <div class="bar-fill" id="bar-delivery"></div>
                                </div>
                                <span id="score-delivery">0</span>
                            </div>
                            <div class="bar-item">
                                <span data-i18n="feedback.visual">Visual</span>
                                <div class="bar">
                                    <div class="bar-fill" id="bar-visual"></div>
                                </div>
                                <span id="score-visual">0</span>
                            </div>
                        </div>
                    </div>
                    
                    <div class="feedback-card glass-card">
                        <h3>&#128221; <span data-i18n="feedback.summary">Summary</span></h3>
                        <p id="fb-summary"></p>
                    </div>
                    
                    <div class="feedback-card glass-card">
                        <h3>&#128170; <span data-i18n="feedback.strengths">Strengths</span></h3>
                        <ul id="fb-strengths"></ul>
                    </div>
                    
                    <div class="feedback-card glass-card">
                        <h3>&#128200; <span data-i18n="feedback.improvements">Areas for Improvement</span></h3>
                        <div id="fb-improvements"></div>
                    </div>
                    
                    <div class="feedback-card glass-card">
                        <div class="question-feedback-header">
                            <h3>&#128161; <span data-i18n="feedback.questions">Question-by-Question Feedback</span></h3>
                            <div class="question-nav-buttons">
                                <button class="question-nav-btn" id="q-prev" disabled>&#8592;</button>
                                <span class="question-feedback-counter" id="question-counter">1 / 1</span>
                                <button class="question-nav-btn" id="q-next">&#8594;</button>
                            </div>
                        </div>
                        <div class="question-feedback-carousel" id="fb-question-feedback">
                            <div class="question-slides" id="question-slides"></div>
                            <div class="question-dots" id="question-dots"></div>
                        </div>
                    </div>
                    
                    <div class="feedback-card glass-card">
                        <h3>&#128249; <span data-i18n="feedback.presence">Visual Presence</span></h3>
                        <div id="fb-visual-analysis"></div>
                    </div>
                    
                    <div class="feedback-card glass-card">
                        <h3>&#128483;&#65039; <span data-i18n="feedback.speech">Speech Analysis</span></h3>
                        <p id="fb-speech-summary"></p>
                        <div id="fb-filler-words" class="filler-words-section"></div>
                    </div>
                    
                    <div class="feedback-card glass-card">
                        <h3>&#127919; <span data-i18n="feedback.nextsteps">Next Steps</span></h3>
                        <ul id="fb-nextsteps"></ul>
                    </div>
                    
                    <div class="print-only-transcript" id="print-transcript-section">
                        <div class="feedback-card">
                            <h3>&#128203; <span data-i18n="feedback.transcript">Full Transcript</span></h3>
                            <div class="print-transcript" id="print-transcript-messages"></div>
                        </div>
                    </div>
                    
                    <div class="feedback-actions">
                        <div class="feedback-actions-row">
                            <button class="btn btn-primary btn-lg btn-glow" id="btn-practice-again">
                                &#128260; <span data-i18n="btn.practice">Practice Again</span>
                            </button>
                            <button class="btn btn-secondary btn-lg" id="btn-view-transcript">
                                &#128203; <span data-i18n="btn.transcript">View Transcript</span>
                            </button>
                        </div>
                        <div class="feedback-actions-row">
                            <button class="btn btn-secondary btn-lg" id="btn-share">
                                &#128279; <span data-i18n="btn.share">Share</span>
                            </button>
                            <button class="btn btn-secondary btn-lg" id="btn-export-pdf">
                                &#128424;&#65039; <span data-i18n="btn.export">Export PDF</span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <footer class="footer">
            <div class="footer-content">
                <span class="footer-brand">&#169; 2026 Young-wouk KIM</span>
                <div class="footer-links">
                    <a id="footer-website-link" href="#" target="_blank" title="Website" data-i18n-title="footer.website">
                        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="currentColor">
                            <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-1 17.93c-3.95-.49-7-3.85-7-7.93 0-.62.08-1.21.21-1.79L9 15v1c0 1.1.9 2 2 2v1.93zm6.9-2.54c-.26-.81-1-1.39-1.9-1.39h-1v-3c0-.55-.45-1-1-1H8v-2h2c.55 0 1-.45 1-1V7h2c1.1 0 2-.9 2-2v-.41c2.93 1.19 5 4.06 5 7.41 0 2.08-.8 3.97-2.1 5.39z"/>
                        </svg>
                    </a>
                    <a href="https://www.linkedin.com/in/young-wouk-kim/" target="_blank" title="LinkedIn">
                        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="currentColor">
                            <path d="M19 3a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h14m-.5 15.5v-5.3a3.26 3.26 0 0 0-3.26-3.26c-.85 0-1.84.52-2.32 1.3v-1.11h-2.79v8.37h2.79v-4.93c0-.77.62-1.4 1.39-1.4a1.4 1.4 0 0 1 1.4 1.4v4.93h2.79M6.88 8.56a1.68 1.68 0 0 0 1.68-1.68c0-.93-.75-1.69-1.68-1.69a1.69 1.69 0 0 0-1.69 1.69c0 .93.76 1.68 1.69 1.68m1.39 9.94v-8.37H5.5v8.37h2.77z"/>
                        </svg>
                    </a>
                </div>
            </div>
        </footer>

        <div class="cookie-banner" id="cookie-banner">
            <div class="cookie-content">
                <span class="cookie-text">&#127850; <span data-i18n="cookie.text">This site uses cookies to enhance your experience. By continuing to use this site, you consent to our use of cookies.</span></span>
                <div class="cookie-actions">
                    <button class="btn btn-sm btn-secondary" id="btn-decline-cookies" data-i18n="btn.decline">Decline</button>
                    <button class="btn btn-sm btn-primary" id="btn-accept-cookies" data-i18n="btn.accept">Accept</button>
                </div>
            </div>
        </div>

        <div class="modal-overlay" id="modal-overlay"></div>
        
        <div class="modal" id="loading-modal" role="dialog" aria-modal="true" aria-label="Loading">
            <div class="spinner"></div>
            <p id="loading-msg">Processing...</p>
        </div>
        
        <div class="modal modal-lg" id="transcript-modal" role="dialog" aria-modal="true" aria-labelledby="transcript-modal-title">
            <div class="modal-header">
                <h3>&#128203; <span id="transcript-modal-title" data-i18n="modal.transcript">Interview Transcript</span></h3>
                <button class="modal-close" aria-label="Close">&#215;</button>
            </div>
            <div class="modal-body-wrapper">
                <div class="modal-body" id="transcript-content"></div>
            </div>
        </div>
        
        <div class="modal modal-md" id="share-modal" role="dialog" aria-modal="true" aria-labelledby="share-modal-title">
            <div class="modal-header">
                <h3>&#128279; <span id="share-modal-title" data-i18n="share.title">Share Your Results</span></h3>
                <button class="modal-close" aria-label="Close">&#215;</button>
            </div>
            <div class="modal-body-wrapper">
                <div class="modal-body share-modal-content">
                    <p class="share-description" data-i18n="share.description">Anyone with this link can view your interview feedback.</p>
                    <div class="share-link-container">
                        <input type="text" class="share-link-input" id="share-link-input" readonly>
                        <button class="btn btn-primary share-copy-btn" id="btn-copy-share-link">
                            &#128203; <span data-i18n="share.copy">Copy</span>
                        </button>
                    </div>
                    <div class="share-divider">
                        <span data-i18n="share.via">Share via</span>
                    </div>
                    <div class="share-social-buttons">
                        <a href="#" id="share-linkedin" class="share-social-btn linkedin" target="_blank">
                            &#128279; <span data-i18n="share.linkedin">LinkedIn</span>
                        </a>
                        <a href="#" id="share-email" class="share-social-btn email">
                            &#9993;&#65039; <span data-i18n="share.email">Email</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>

        </div>
    </div>

    <!-- Core: foundation modules -->
    <script src="js/core/i18n.js?v=<?= $cacheBuster ?>"></script>
    <script src="js/core/config.js?v=<?= $cacheBuster ?>"></script>
    <script src="js/core/utils.js?v=<?= $cacheBuster ?>"></script>

    <!-- Services: API & device abstraction layer -->
    <script src="js/services/api.js?v=<?= $cacheBuster ?>"></script>
    <script src="js/services/tts-service.js?v=<?= $cacheBuster ?>"></script>
    <script src="js/services/voice-service.js?v=<?= $cacheBuster ?>"></script>
    <script src="js/services/video-service.js?v=<?= $cacheBuster ?>"></script>

    <!-- Features: UI managers & rendering -->
    <script src="js/features/feedback-utils.js?v=<?= $cacheBuster ?>"></script>
    <script src="js/features/feedback-renderer.js?v=<?= $cacheBuster ?>"></script>
    <script src="js/features/history-manager.js?v=<?= $cacheBuster ?>"></script>
    <script src="js/features/upload-manager.js?v=<?= $cacheBuster ?>"></script>
    <script src="js/features/interview-manager.js?v=<?= $cacheBuster ?>"></script>
    <script src="js/features/feedback-manager.js?v=<?= $cacheBuster ?>"></script>
    <script src="js/features/pdf-export.js?v=<?= $cacheBuster ?>"></script>

    <!-- Entry point -->
    <script src="js/app.js?v=<?= $cacheBuster ?>"></script>
</body>
</html>