<?php
/**
 * share.php
 * Shared Interview Feedback Page
 * Read-only view for shared feedback results
 */

require_once __DIR__ . '/src/config.php';

$cacheBuster = time();
$appName = PROJECT_NAME;
$appTagline = PROJECT_TAGLINE;

// Get base path for assets - works regardless of URL structure
$scriptDir = dirname($_SERVER['SCRIPT_NAME']);
$basePath = rtrim($scriptDir, '/');
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>Shared Interview Feedback | <?= htmlspecialchars($appName) ?></title>
    <meta name="description" content="View AI-powered mock interview feedback shared via <?= htmlspecialchars($appName) ?>.">
    <meta name="robots" content="noindex, nofollow">
    <link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>&#127919;</text></svg>">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="<?= $basePath ?>/css/core/base.css?v=<?= $cacheBuster ?>">
    <link rel="stylesheet" href="<?= $basePath ?>/css/core/components.css?v=<?= $cacheBuster ?>">
    <link rel="stylesheet" href="<?= $basePath ?>/css/core/layout.css?v=<?= $cacheBuster ?>">
    <link rel="stylesheet" href="<?= $basePath ?>/css/pages/feedback.css?v=<?= $cacheBuster ?>">
    <link rel="stylesheet" href="<?= $basePath ?>/css/features/share.css?v=<?= $cacheBuster ?>">
    <link rel="stylesheet" href="<?= $basePath ?>/css/overrides/responsive.css?v=<?= $cacheBuster ?>">
    <style>
        :root {
            --app-print-header: "<?= htmlspecialchars($appName) ?> - Interview Feedback Report";
            --app-print-footer: "Generated by <?= htmlspecialchars($appName) ?> - <?= htmlspecialchars($appTagline) ?>";
        }
    </style>
</head>
<body>
    <div class="bg-shapes">
        <div class="bg-shape bg-shape-1"></div>
        <div class="bg-shape bg-shape-2"></div>
        <div class="bg-shape bg-shape-3"></div>
    </div>

    <div class="share-page" id="app">
        <header class="header">
            <div class="header-content">
                <div class="share-header-left">
                    <a href="<?= $basePath ?>/" class="logo">
                        <span class="logo-text"><?= htmlspecialchars($appName) ?></span>
                    </a>
                    <span class="share-badge" id="share-header-title">Shared Feedback</span>
                </div>
                <select id="language-select" class="lang-select">
                    <option value="en">&#127468;&#127463; EN</option>
                    <option value="fr">&#127467;&#127479; FR</option>
                </select>
            </div>
        </header>

        <main class="share-main">
            <div class="share-container">
                <div id="share-loading" class="share-loading">
                    <div class="spinner"></div>
                    <p class="share-loading-text">Loading feedback...</p>
                </div>

                <div id="share-error" class="share-error hidden">
                    <div class="share-error-icon">&#128533;</div>
                    <h2 class="share-error-title" id="share-error-title">Share Not Found</h2>
                    <p class="share-error-message" id="share-error-message">This share link does not exist or has been removed.</p>
                    <a href="<?= $basePath ?>/" class="btn btn-primary btn-lg" id="share-error-back">&larr; Go to <?= htmlspecialchars($appName) ?></a>
                </div>

                <div id="share-content" class="hidden">
                    <div class="share-meta">
                        <div class="share-position-badge" id="share-position">Interview</div>
                        <div class="share-date" id="share-date"></div>
                    </div>
                    <div id="share-feedback-content" class="feedback-content"></div>
                </div>
            </div>
        </main>

        <footer class="footer">
            <div class="footer-content">
                <span class="footer-brand">&#169; 2026 Young-wouk KIM</span>
                <div class="footer-links">
                    <a id="footer-website-link" href="https://wouk1805.com" target="_blank" title="Website" data-i18n-title="footer.website">
                        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="currentColor">
                            <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-1 17.93c-3.95-.49-7-3.85-7-7.93 0-.62.08-1.21.21-1.79L9 15v1c0 1.1.9 2 2 2v1.93zm6.9-2.54c-.26-.81-1-1.39-1.9-1.39h-1v-3c0-.55-.45-1-1-1H8v-2h2c.55 0 1-.45 1-1V7h2c1.1 0 2-.9 2-2v-.41c2.93 1.19 5 4.06 5 7.41 0 2.08-.8 3.97-2.1 5.39z"/>
                        </svg>
                    </a>
                    <a href="https://www.linkedin.com/in/young-wouk-kim/" target="_blank" title="LinkedIn">
                        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="currentColor">
                            <path d="M19 3a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h14m-.5 15.5v-5.3a3.26 3.26 0 0 0-3.26-3.26c-.85 0-1.84.52-2.32 1.3v-1.11h-2.79v8.37h2.79v-4.93c0-.77.62-1.4 1.39-1.4a1.4 1.4 0 0 1 1.4 1.4v4.93h2.79M6.88 8.56a1.68 1.68 0 0 0 1.68-1.68c0-.93-.75-1.69-1.68-1.69a1.69 1.69 0 0 0-1.69 1.69c0 .93.76 1.68 1.69 1.68m1.39 9.94v-8.37H5.5v8.37h2.77z"/>
                        </svg>
                    </a>
                </div>
            </div>
        </footer>
    </div>

    <script>
        window.PREPGENIUS_BASE_PATH = '<?= $basePath ?>';
        window.APP_NAME = '<?= htmlspecialchars($appName, ENT_QUOTES) ?>';
        window.APP_TAGLINE = '<?= htmlspecialchars($appTagline, ENT_QUOTES) ?>';
    </script>
    <script src="<?= $basePath ?>/js/core/i18n.js?v=<?= $cacheBuster ?>"></script>
    <script src="<?= $basePath ?>/js/core/config.js?v=<?= $cacheBuster ?>"></script>
    <script src="<?= $basePath ?>/js/core/utils.js?v=<?= $cacheBuster ?>"></script>
    <script src="<?= $basePath ?>/js/features/feedback-utils.js?v=<?= $cacheBuster ?>"></script>
    <script src="<?= $basePath ?>/js/features/feedback-renderer.js?v=<?= $cacheBuster ?>"></script>
    <script src="<?= $basePath ?>/js/share.js?v=<?= $cacheBuster ?>"></script>
</body>
</html>